CDC *tex_Tile = GRRead("Sprites/Tile.GR.Z");
CDC *tex_Brick = GRRead("Sprites/Brick.GR.Z");
CDC *tex_Coin1 = GRRead("Sprites/Coin/Coin1.GR.Z");
CDC *tex_Coin2 = GRRead("Sprites/Coin/Coin2.GR.Z");


CDC *tex_BrickWall = GRRead("Sprites/Tiles/Building/BrickWall.GR.Z");
CDC *tex_BrickWall_Door = GRRead("Sprites/Tiles/Building/BrickWallDoor.GR.Z");
CDC *tex_BrickWall_Window = GRRead("Sprites/Tiles/Building/BrickWallWindow.GR.Z");
CDC *tex_BrickWall_Roof = GRRead("Sprites/Tiles/Building/BrickWallRoof.GR.Z");

CDC *tex_BrickWall_WaterL = GRRead("Sprites/Tiles/Building/Sewers/BrickWallWaterL.GR.Z");
CDC *tex_BrickWall_WaterR = GRRead("Sprites/Tiles/Building/Sewers/BrickWallWaterR.GR.Z");

CDC *tex_Tile_Road = GRRead("Sprites/Tiles/Floor/TileRoad.GR.Z");
CDC *tex_Tile_Road_Left = GRRead("Sprites/Tiles/Floor/TileRoadLeft.GR.Z");
CDC *tex_Tile_Road_Right = GRRead("Sprites/Tiles/Floor/TileRoadRight.GR.Z");
CDC *tex_Tile_Road_Hole = GRRead("Sprites/Tiles/Floor/TileRoadHole.GR.Z");
CDC *tex_Tile_Road_Hole_Open = GRRead("Sprites/Tiles/Floor/TileRoadHoleOpen.GR.Z");

CDC *tex_Tile_Water = GRRead("Sprites/Tiles/Floor/Sewers/TileWater.GR.Z");
CDC *tex_Tile_Water_Left = GRRead("Sprites/Tiles/Floor/Sewers/TileWaterLeft.GR.Z");
CDC *tex_Tile_Water_Right = GRRead("Sprites/Tiles/Floor/Sewers/TileWaterRight.GR.Z"); 

CDC *tex_Tile_Sewer = GRRead("Sprites/Tiles/Floor/Sewers/Tile.GR.Z");


CDC *tex_BrickHole_BL = GRRead("Sprites/Tiles/Building/Sewers/BrickHoleBL.GR.Z");
CDC *tex_BrickHole_BR = GRRead("Sprites/Tiles/Building/Sewers/BrickHoleBR.GR.Z");
CDC *tex_BrickHole_TL = GRRead("Sprites/Tiles/Building/Sewers/BrickHoleTL.GR.Z");
CDC *tex_BrickHole_TR = GRRead("Sprites/Tiles/Building/Sewers/BrickHoleTR.GR.Z");


CDC *tex_Question1 = GRRead("Sprites/Tiles/Question1.GR.Z");
CDC *tex_Question2 = GRRead("Sprites/Tiles/Question2.GR.Z");
CDC *tex_Question3 = GRRead("Sprites/Tiles/Question3.GR.Z");


CDC *tex_Cloud = GRRead("Sprites/Cloud.GR.Z");
CDC *tex_Sun = GRRead("Sprites/Sun.GR.Z");

CDC *tex_PMan_IdleRight = GRRead("Sprites/PMan/IdleRight.GR.Z");
CDC *tex_PMan_Walk1Right = GRRead("Sprites/PMan/Walk1Right.GR.Z");
CDC *tex_PMan_Walk2Right = GRRead("Sprites/PMan/Walk2Right.GR.Z");
CDC *tex_PMan_Walk3Right = GRRead("Sprites/PMan/Walk3Right.GR.Z");

CDC *tex_PMan_IdleLeft = GRRead("Sprites/PMan/IdleLeft.GR.Z");
CDC *tex_PMan_Walk1Left = GRRead("Sprites/PMan/Walk1Left.GR.Z");
CDC *tex_PMan_Walk2Left = GRRead("Sprites/PMan/Walk2Left.GR.Z");
CDC *tex_PMan_Walk3Left = GRRead("Sprites/PMan/Walk3Left.GR.Z");

CDC *tex_PMan_JumpLeft = GRRead("Sprites/PMan/JumpLeft.GR.Z");
CDC *tex_PMan_JumpRight = GRRead("Sprites/PMan/JumpRight.GR.Z");

CDC *tex_PMan_Big_IdleRight = GRRead("Sprites/PMan/Big/IdleRight.GR.Z");
CDC *tex_PMan_Big_Walk1Right = GRRead("Sprites/PMan/Big/Walk1Right.GR.Z");
CDC *tex_PMan_Big_Walk2Right = GRRead("Sprites/PMan/Big/Walk2Right.GR.Z");
CDC *tex_PMan_Big_Walk3Right = GRRead("Sprites/PMan/Big/Walk3Right.GR.Z");

CDC *tex_PMan_Big_IdleLeft = GRRead("Sprites/PMan/Big/IdleLeft.GR.Z");
CDC *tex_PMan_Big_Walk1Left = GRRead("Sprites/PMan/Big/Walk1Left.GR.Z");
CDC *tex_PMan_Big_Walk2Left = GRRead("Sprites/PMan/Big/Walk2Left.GR.Z");
CDC *tex_PMan_Big_Walk3Left = GRRead("Sprites/PMan/Big/Walk3Left.GR.Z");

CDC *tex_PMan_Big_JumpLeft = GRRead("Sprites/PMan/Big/JumpLeft.GR.Z");
CDC *tex_PMan_Big_JumpRight = GRRead("Sprites/PMan/Big/JumpRight.GR.Z");

CDC *tex_PMan_Big_DuckLeft = GRRead("Sprites/PMan/Big/DuckLeft.GR.Z");
CDC *tex_PMan_Big_DuckRight = GRRead("Sprites/PMan/Big/DuckRight.GR.Z");



CDC *tex_PMan_Flower_IdleRight = GRRead("Sprites/PMan/Big/Flower/IdleRight.GR.Z");
CDC *tex_PMan_Flower_Walk1Right = GRRead("Sprites/PMan/Big/Flower/Walk1Right.GR.Z");
CDC *tex_PMan_Flower_Walk2Right = GRRead("Sprites/PMan/Big/Flower/Walk2Right.GR.Z");
CDC *tex_PMan_Flower_Walk3Right = GRRead("Sprites/PMan/Big/Flower/Walk3Right.GR.Z");

CDC *tex_PMan_Flower_JumpRight = GRRead("Sprites/PMan/Big/Flower/JumpRight.GR.Z");
CDC *tex_PMan_Flower_DuckRight = GRRead("Sprites/PMan/Big/Flower/DuckRight.GR.Z");

CDC *tex_PMan_Flower_IdleLeft = GRRead("Sprites/PMan/Big/Flower/IdleLeft.GR.Z");
CDC *tex_PMan_Flower_Walk1Left = GRRead("Sprites/PMan/Big/Flower/Walk1Left.GR.Z");
CDC *tex_PMan_Flower_Walk2Left = GRRead("Sprites/PMan/Big/Flower/Walk2Left.GR.Z");
CDC *tex_PMan_Flower_Walk3Left = GRRead("Sprites/PMan/Big/Flower/Walk3Left.GR.Z");

CDC *tex_PMan_Flower_JumpLeft = GRRead("Sprites/PMan/Big/Flower/JumpLeft.GR.Z");
CDC *tex_PMan_Flower_DuckLeft = GRRead("Sprites/PMan/Big/Flower/DuckLeft.GR.Z");


CDC *tex_Slug_Walk1Left = GRRead("Sprites/Slug/Walk1Left.GR.Z");
CDC *tex_Slug_Walk2Left = GRRead("Sprites/Slug/Walk2Left.GR.Z");
CDC *tex_Slug_Walk1Right = GRRead("Sprites/Slug/Walk1Right.GR.Z");
CDC *tex_Slug_Walk2Right = GRRead("Sprites/Slug/Walk2Right.GR.Z");

CDC *tex_Turtle_Walk1Left = GRRead("Sprites/Turtle/Walk1Left.GR.Z");
CDC *tex_Turtle_Walk2Left = GRRead("Sprites/Turtle/Walk2Left.GR.Z");
CDC *tex_Turtle_Walk1Right = GRRead("Sprites/Turtle/Walk1Right.GR.Z");
CDC *tex_Turtle_Walk2Right = GRRead("Sprites/Turtle/Walk2Right.GR.Z");

CDC *tex_Turtle_Shell = GRRead("Sprites/Turtle/Shell.GR.Z");

CDC *tex_Powerup_Shroom = GRRead("Sprites/PowerUps/Shroom.GR.Z");
CDC *tex_Powerup_Flower1 = GRRead("Sprites/Flower/Flower1.GR.Z");
CDC *tex_Powerup_Flower2 = GRRead("Sprites/Flower/Flower2.GR.Z");



CDC *tex_Particle_BrickLeft = GRRead("Sprites/Particles/BrickLeft.GR.Z");
CDC *tex_Particle_BrickRight = GRRead("Sprites/Particles/BrickRight.GR.Z");

CDC *tex_Particle_Coin1 = GRRead("Sprites/Particles/Coin1.GR.Z");
CDC *tex_Particle_Coin2 = GRRead("Sprites/Particles/Coin2.GR.Z");
CDC *tex_Particle_Coin3 = GRRead("Sprites/Particles/Coin3.GR.Z");

CDC *tex_Fireball1 = GRRead("Sprites/Fireball/1.GR.Z");
CDC *tex_Fireball2 = GRRead("Sprites/Fireball/2.GR.Z");
CDC *tex_Fireball3 = GRRead("Sprites/Fireball/3.GR.Z");
CDC *tex_Fireball4 = GRRead("Sprites/Fireball/4.GR.Z");

CDC *tex_EndLevel_Bar = GRRead("Sprites/EndLevel/Bar.GR");
CDC *tex_EndLevel_Zoomer = GRRead("Sprites/EndLevel/Zoomer.GR");

CDC *tex_FadeIn1 = GRRead("Sprites/Blackout/Blackout1.GR");
CDC *tex_FadeIn2 = GRRead("Sprites/Blackout/Blackout2.GR");

CDC *tex_Platform = GRRead("Sprites/Platform.GR.Z");

CDC *tex_Tile_Platform = GRRead("Sprites/Tiles/Platform.GR.Z");

CDC *tex_Mansion_Wall = GRRead("Sprites/Tiles/Mansion/Wall.GR.Z");
CDC *tex_Mansion_Wall_Down = GRRead("Sprites/Tiles/Mansion/WallDown.GR.Z");
CDC *tex_Mansion_Wall_Top = GRRead("Sprites/Tiles/Mansion/WallTop.GR.Z");

CDC *tex_MansionWall_Window_BL = GRRead("Sprites/Tiles/Mansion/WallWindowBL.GR.Z");
CDC *tex_MansionWall_Window_BR = GRRead("Sprites/Tiles/Mansion/WallWindowBR.GR.Z");
CDC *tex_MansionWall_Window_TL = GRRead("Sprites/Tiles/Mansion/WallWindowTL.GR.Z");
CDC *tex_MansionWall_Window_TR = GRRead("Sprites/Tiles/Mansion/WallWindowTR.GR.Z");

CDC *tex_MansionWall_Entrance_BL = GRRead("Sprites/Tiles/Mansion/WallEntranceBL.GR.Z");
CDC *tex_MansionWall_Entrance_BR = GRRead("Sprites/Tiles/Mansion/WallEntranceBR.GR.Z");
CDC *tex_MansionWall_Entrance_TL = GRRead("Sprites/Tiles/Mansion/WallEntranceTL.GR.Z");
CDC *tex_MansionWall_Entrance_TR = GRRead("Sprites/Tiles/Mansion/WallEntranceTR.GR.Z");

CDC *tex_MansionTemple_Pillar = GRRead("Sprites/Tiles/Mansion/Pillar.GR.Z");
CDC *tex_MansionTemple_PillarUp = GRRead("Sprites/Tiles/Mansion/PillarUp.GR.Z");
CDC *tex_MansionTemple_PillarDown = GRRead("Sprites/Tiles/Mansion/PillarDown.GR.Z");

CDC *tex_MansionTemple_Roof1Left = GRRead("Sprites/Tiles/Mansion/Temple1Left.GR.Z");
CDC *tex_MansionTemple_Roof1Right = GRRead("Sprites/Tiles/Mansion/Temple1Right.GR.Z");
CDC *tex_MansionTemple_Roof2Left = GRRead("Sprites/Tiles/Mansion/Temple2Left.GR.Z");
CDC *tex_MansionTemple_Roof2Right = GRRead("Sprites/Tiles/Mansion/Temple2Right.GR.Z");


CDC *tex_MansionTemple_StatueBL = GRRead("Sprites/Tiles/Mansion/TempleStatueBL.GR.Z");
CDC *tex_MansionTemple_StatueBR = GRRead("Sprites/Tiles/Mansion/TempleStatueBR.GR.Z");
CDC *tex_MansionTemple_StatueTL = GRRead("Sprites/Tiles/Mansion/TempleStatueTL.GR.Z");
CDC *tex_MansionTemple_StatueTR = GRRead("Sprites/Tiles/Mansion/TempleStatueTR.GR.Z");


CDC *tex_SpinLaser_Ball = GRRead("Sprites/SpinLaser/Ball.GR.Z");